Ci/cd
Accessible-Technology-in-Sign/PopSign pull request #57
Opened 2024-02-02 00:12 UTC by snarayan43

Although called ci/cd, there are no ci/cd changes in this pr
In this pr we:
- Updated UI design - changed screens, fonts and buttons in the game to make it more accessible to color blind individuals
- Updated videos to new DPAN videos
- Tested on Google Pixel 4

2024-02-19 22:23 UTC, guru-desh commented on Assets/Plugins/.DS_Store
Can you remove the .DS_Store files?

2024-02-19 22:24 UTC, guru-desh commented on Assets/FramesToVideo/.DS_Store
Another .DS_Store file here as well

2024-02-19 22:24 UTC, guru-desh commented on Assets/.DS_Store
Another .DS_Store file here as well

2024-02-19 22:49 UTC, guru-desh requested changes

2024-02-19 22:49 UTC, guru-desh commented on .gitignore
> -.DS_Store
Why was .DS_Store removed from .gitignore?

2024-02-19 22:49 UTC, guru-desh commented on mono_crash.mem.49121.1.blob
What does this binary file do?

2024-02-19 22:49 UTC, guru-desh commented on mono_crash.mem.49596.1.blob
What does this binary file do?

2024-02-19 22:49 UTC, guru-desh commented on .github/workflows/activation.yml
If this PR doesn't include CI/CD, then why is this here?

2024-02-19 22:49 UTC, guru-desh commented on requirements.txt
What is the point of this requirements.txt?

2024-02-29 23:45 UTC, snarayan43 commented on .gitignore
> -.DS_Store
I am not sure. Would you like me to add it back, and how would I go about it?

2024-02-29 23:45 UTC, snarayan43 commented on Assets/.DS_Store
Done

2024-02-29 23:45 UTC, snarayan43 commented on Assets/FramesToVideo/.DS_Store
Done

2024-02-29 23:45 UTC, snarayan43 commented on Assets/Plugins/.DS_Store
Done

2024-02-29 23:55 UTC, snarayan43 commented on requirements.txt
Khushi wanted to see the libraries I had on my laptop because something wasn't working - I can't remove it because the problem was resolved

2024-03-01 00:02 UTC, snarayan43 commented on mono_crash.mem.49121.1.blob
It might have been added when we added new fonts, but deleting it doesn't make a difference, so I can remove it

2024-03-01 00:03 UTC, snarayan43 commented on mono_crash.mem.49596.1.blob
It might have been added when we added new fonts, but deleting it doesn't make a difference, so I can remove it

2024-03-01 00:12 UTC, snarayan43 commented on .github/workflows/activation.yml
I am going to remove these files - Im not sure how they got in there

2024-03-01 19:35 UTC, guru-desh commented on .gitignore
> -.DS_Store
Yeah please add .DS_Store back into the .gitignore

2024-03-01 19:35 UTC, guru-desh commented on .github/workflows/activation.yml
Please let me know when it's been removed!

2024-03-01 19:35 UTC, guru-desh commented on mono_crash.mem.49596.1.blob
Please let me know when it's been removed!

2024-03-01 19:35 UTC, guru-desh commented on mono_crash.mem.49121.1.blob
Please let me know when it's been removed!

2024-03-01 19:36 UTC, guru-desh commented on requirements.txt
>  I can't remove it because the problem was resolved

If the problem was resolved, how does that mean that you cannot remove the requirements.txt?

2024-10-16 00:16 UTC, merged